name: 'Deploy ticketapi'
description: 'Runs the Deployment'
inputs:
  appid:
    description: 'Deployed container ID'
    required: true
    default: 'none_given'
outputs:
  time: #
    description: 'The time we received'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appid }}