# Generated by Django 6.0.6 on 2026-06-14 21:06
from django.db import migrations
from django.db.models import Q

def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    attendant_group, _ = Group.objects.get_or_create(name='Attendants')
    customer_group, _ = Group.objects.get_or_create(name='Customers')

def remove_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(Q(name='Attendants') | Q(name='Customers')).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, remove_groups_and_permissions),
    ]
