name: Deploy Docker Compose to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Copy Files via SCP to Oracle Linux
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/app"

      - name: SSH and Restart Docker Compose Stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            
            if [ ! -d "DjangoTechnicalSupport" ]; then
              git clone git@github.com:cpluiz/DjangoTechnicalSupport.git
            else
              git fetch --all
              git reset --hard origin/main
            fi
            
            # Builda a aplicação com os novos arquivos baixados e reinicia os containers
            docker compose up -d --build --remove-orphans